"""updated job modal

Revision ID: 07ce0abf4a09
Revises: 417c318b24d3
Create Date: 2026-01-30 10:01:35.554375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ce0abf4a09'
down_revision = '417c318b24d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'join_date')
    # ### end Alembic commands ###

