"""modal update

Revision ID: 1f985f9fc10f
Revises: eda546616966
Create Date: 2026-02-03 04:37:37.819348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f985f9fc10f'
down_revision = 'eda546616966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

