"""update schema

Revision ID: 24e6df81396e
Revises: cbd2cee83d09
Create Date: 2026-01-26 02:28:11.221951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e6df81396e'
down_revision = 'cbd2cee83d09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert business_id from VARCHAR to INTEGER with explicit casting
    # This assumes existing business_id values are numeric strings
    op.execute("ALTER TABLE admin ALTER COLUMN business_id TYPE INTEGER USING business_id::INTEGER")
    op.create_foreign_key(None, 'admin', 'business', ['business_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.alter_column('admin', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###

