"""updated job modal

Revision ID: 34d9db299749
Revises: 69c50d01fcde
Create Date: 2026-01-31 18:00:41.459518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d9db299749'
down_revision = '69c50d01fcde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

