"""job application modal update

Revision ID: 3d10c629cb78
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 20:00:34.705746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d10c629cb78'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first in PostgreSQL
    workstatus_enum = sa.Enum('assigned', 'completed', name='workstatus')
    workstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the enum type
    op.add_column('job_applications', sa.Column('work_status', workstatus_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    op.drop_column('job_applications', 'work_status')
    
    # Then drop the enum type
    workstatus_enum = sa.Enum('assigned', 'completed', name='workstatus')
    workstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

