"""updated job modal

Revision ID: 417c318b24d3
Revises: 24e6df81396e
Create Date: 2026-01-30 09:13:28.691868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417c318b24d3'
down_revision = '24e6df81396e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create PostgreSQL ENUM type before using it (required for PostgreSQL)
    jobapplicationstatus = sa.Enum('pending', 'approved', 'rejected', name='jobapplicationstatus')
    jobapplicationstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('job_applications', sa.Column('approved_status', sa.Enum('pending', 'approved', 'rejected', name='jobapplicationstatus', create_type=False), nullable=False, server_default='pending'))
    op.drop_column('jobs', 'email')
    op.drop_column('jobs', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('job_applications', 'approved_status')
    sa.Enum('pending', 'approved', 'rejected', name='jobapplicationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

