"""updated job modal

Revision ID: 69c50d01fcde
Revises: f7415da237fe
Create Date: 2026-01-31 17:59:22.655901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c50d01fcde'
down_revision = 'f7415da237fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

