"""updated job modal

Revision ID: bfb9cb0cb355
Revises: 34d9db299749
Create Date: 2026-01-31 18:01:31.914991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfb9cb0cb355'
down_revision = '34d9db299749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('language', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

