"""admin login

Revision ID: cf5f00f751b6
Revises: ec46f5ea3035
Create Date: 2026-02-02 03:17:12.603195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5f00f751b6'
down_revision = 'ec46f5ea3035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###

