"""job-application modal

Revision ID: dafe5fd5e2f1
Revises: fe92a5ffa707
Create Date: 2026-02-07 20:31:36.431592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafe5fd5e2f1'
down_revision = 'fe92a5ffa707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'is_active')
    # ### end Alembic commands ###

