"""user modal

Revision ID: e0551cca5b93
Revises: 1f985f9fc10f
Create Date: 2026-02-07 16:41:18.222122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0551cca5b93'
down_revision = '1f985f9fc10f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing enum types (gender, employmenttype, userroleenum already exist from workers/admin)
    # postgresql.ENUM with create_type=False so we don't CREATE TYPE again
    gender_type = postgresql.ENUM('male', 'female', 'other', name='gender', create_type=False)
    employment_type = postgresql.ENUM('full_time', 'part_time', 'contract', 'freelancer', name='employmenttype', create_type=False)
    userrole_enum = postgresql.ENUM('admin', 'worker', name='userroleenum', create_type=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('gender', gender_type, nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('employment_type', employment_type, nullable=True),
    sa.Column('user_role', userrole_enum, nullable=True),
    sa.Column('worker_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # Migrate job_applications off workers BEFORE dropping workers (drop FK first)
    op.add_column('job_applications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('job_applications_worker_id_fkey'), 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'worker_id')
    op.create_foreign_key('job_applications_user_id_fkey', 'job_applications', 'users', ['user_id'], ['id'])
    # Migrate jobs off admin BEFORE dropping admin (drop FK first)
    op.drop_constraint(op.f('jobs_admin_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['admin_id'], ['id'])
    # Now safe to drop workers and admin
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_admin_id_fkey'), 'jobs', 'admin', ['admin_id'], ['id'])
    op.add_column('job_applications', sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key(op.f('job_applications_worker_id_fkey'), 'job_applications', 'workers', ['worker_id'], ['id'])
    op.drop_column('job_applications', 'user_id')
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('admin_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender'), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'worker', name='userroleenum'), server_default=sa.text("'admin'::userroleenum"), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='admin_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender'), autoincrement=False, nullable=False),
    sa.Column('availability', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('employment_type', postgresql.ENUM('full_time', 'part_time', 'contract', 'freelancer', name='employmenttype'), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('admin', 'worker', name='userroleenum'), server_default=sa.text("'worker'::userroleenum"), autoincrement=False, nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('workers_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey'))
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

