"""update worker modal

Revision ID: ec46f5ea3035
Revises: bfb9cb0cb355
Create Date: 2026-01-31 18:38:33.832425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec46f5ea3035'
down_revision = 'bfb9cb0cb355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'password')
    # ### end Alembic commands ###

