"""modal and api access control

Revision ID: eda546616966
Revises: cf5f00f751b6
Create Date: 2026-02-03 04:22:00.040449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eda546616966'
down_revision = 'cf5f00f751b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('from_date_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('jobs', sa.Column('to_date_time', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('jobs', 'workers_hired',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobs', 'tone_requirement')
    op.drop_column('jobs', 'join_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('join_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('tone_requirement', postgresql.ENUM('professional', 'casual', 'formal', 'friendly', 'empathetic', name='tonerequirement'), autoincrement=False, nullable=False))
    op.alter_column('jobs', 'workers_hired',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jobs', 'to_date_time')
    op.drop_column('jobs', 'from_date_time')
    # ### end Alembic commands ###

