"""job application modal update

Revision ID: fa04801ba017
Revises: 3d10c629cb78
Create Date: 2026-02-11 21:33:27.891251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa04801ba017'
down_revision = '3d10c629cb78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first in PostgreSQL
    paymentstatus_enum = sa.Enum('pending', 'paid', 'rejected', name='paymentstatus')
    paymentstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the enum type
    op.add_column('job_applications', sa.Column('payment_status', paymentstatus_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    op.drop_column('job_applications', 'payment_status')
    
    # Then drop the enum type
    paymentstatus_enum = sa.Enum('pending', 'paid', 'rejected', name='paymentstatus')
    paymentstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

