"""job-application modal

Revision ID: fe92a5ffa707
Revises: e0551cca5b93
Create Date: 2026-02-07 20:28:03.230949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe92a5ffa707'
down_revision = 'e0551cca5b93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('worker_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('job_applications_user_id_fkey'), 'job_applications', type_='foreignkey')
    op.create_foreign_key(None, 'job_applications', 'users', ['worker_id'], ['id'])
    op.drop_column('job_applications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key(op.f('job_applications_user_id_fkey'), 'job_applications', 'users', ['user_id'], ['id'])
    op.drop_column('job_applications', 'worker_id')
    # ### end Alembic commands ###

